import { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import * as ethers from "ethers";
import { getAllMembers } from "../util/skillwallet";
import { postPayrollToIPFS } from "../util/IPFS";
const Home: NextPage = () => {
  console.log("sessionstorage");
  const communityAddress =
    typeof window !== "undefined" &&
    window.sessionStorage.getItem("skillWallet") &&
    JSON.parse(window.sessionStorage.getItem("skillWallet") as string)
      .partnersAgreementKey.communityAddress;
  useEffect(() => {
    async function load() {
      // Prompt user for account connections
      const provider = new ethers.providers.Web3Provider(
        window.ethereum,
        "any"
      );
      await provider.send("eth_requestAccounts", []);
      const signer = provider.getSigner();
      console.log("Account:", await signer.getAddress());
      const tmp = window.sessionStorage.getItem("skillWallet");
      window.addEventListener("onSkillwalletLogin", () =>
        console.log("hiiddd")
      );
    }
    load();
  });
  typeof window !== "undefined" &&
    window.addEventListener("storage", () => {
      // When local storage changes, dump the list to
      // the console.
      console.log(JSON.parse(window.localStorage.getItem("sampleList")));
    });
  //isCoreTeamMember -> can edit hires or not
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        hi
        {/*@ts-ignore*/}
        <sw-auth
          partner-key="75122500c30d00dd83c1a2c306d3e6e298ba70b7" //"212ffeaad53d44d5d685c17a48935a71e32b862f" //f407f2a2b646a7940f159ce27c2c9427c97dc853"
          use-dev="true"
          onchange={() => console.log("changee")}
          onClick={() => console.log("changeeclick")}
        >
          {/*@ts-ignore*/}
        </sw-auth>
      </main>
    </div>
  );
};

export default Home;
